### ISSUE TITLE
Is Klaro being developed and updated? 

### ISSUE THREAD

**Issue by caioricciuti** [klaro-org/klaro-js#408]
Hello, I use Klaro and I would like to know if the owners of the project Kiprotect still give Klaro attention. I use the tool but unfortunately, I don't have enough knowledge to contribute. I'm extremely grateful for all your work and in my opinion, Klaro is the best open source consent tool available, that's why I'm asking if you are still on it.

Thank you very much for all colabs and people that make this happen!

**Comment by mbsouth** [comment]
+1

**Comment by javalexG** [comment]
+1

**Comment by sahib-afk** [comment]
> if the owners of the project Kiprotect still give Klaro attention

Judging by the amount of tumbleweed on here, which exceeds the number of (qualified) replies to your question by far, I fear the worst.

**Comment by openmindculture** [comment]
Same problem here. Trying to find out how to make `contextualConsentOnly` work with an Instagram feed provided by juicer.io, as all working `contextualConsent` examples seem to focus on YouTube and Twitter. When trying to decide if I should open a new issue, a found a lot of similar, but unanswered issues, after the helpful support activity back in 2021.

**Comment by caioricciuti** [comment]
I'll close this issue, since it' clear that Klaro's was abandoned... 

Looks like this one https://github.com/orestbida/cookieconsent is a Klaro's fork and works quite well. 

Cheers all!
