### ISSUE TITLE
Google Consent Mode v2

### ISSUE THREAD

**Issue by Lynn-777** [klaro-org/klaro-js#496]
I am currently looking for instructions on how to correctly implement Consent Mode v2 using Klaro. Do you plan to integrate the necessary parameters into Klaro directly? If not, could you please provide me with guidance on how to manually implement these parameters myself?

Thank you in advance for your assistance.

**Comment by bojko91** [comment]
See this: https://measureschool.com/cookie-consent-banner/

IDK if it ok to do with that way "Adding Variables to the Consent State" i put the variables in the new sections that google want. For now i think is working good, but.

**Comment by kocjs** [comment]
@bojko91  I have tried to follow the above guide. However, in my case the if I deny, and continue to surf, i see google analytics cookies getting added. That should not be. If i navigate the site without accepting or denying the cookie popup does not show up some times.

**Comment by adewes** [comment]
Thanks everyone, I'm working on an updated guideline for this, will update here once it's online!

**Comment by liayn** [comment]
Official guide, in case somebody needs it: https://developers.google.com/tag-platform/security/guides/consent?consentmode=advanced

**Comment by corentinbettiol** [comment]
Our usecase:

- Allow ga cookie when user loads the page (`default: true` & `optOut: true`).
- Keep gtags values to `declined`.
- If user clicks on "Accept", then change the gtags values to `enabled`.

We went with using the `onAccept` only when `confirm: true` (only way to know that the user clicked on the Accept button, found by reading the object properties in the console because it's *nowhere* on the docs) for setting the gtag values to "enabled".

**Comment by adewes** [comment]
Hey @liayn, @corentinbettiol, please check out our new tutorial [here](https://klaro.org/docs/tutorials/google_tag_manager). It explains how consent mode v2 works with Klaro and gives an example config, I tested with Tag assistant the the new consent settings are propagated correctly.

If you have any other questions please let me know!

**Comment by 01Kuzma** [comment]
@adewes , 
tell me please, does the klaro.js support the:

```
   functionality_storage
   personalization_storage
   security_storage
```

I've successfully implemented the the banner configuration with your latest tutorial, but debugging with GTM shoes only these storages:

```
ad_storage
analytics_storage
ad_user_data
ad_personalization
```

Or we do not need them?
