### ISSUE TITLE
Inquiry Regarding Current Maintenance Status of Repository

### ISSUE THREAD

**Issue by MelchnerRoman** [klaro-org/klaro-js#498]
Hello!

I hope this message finds you well. I am writing to inquire about the current maintenance status of the [klaro-js] repository. 

I have been following this repository for some time now and have noticed that there have been no recent updates or commits for a while. This repository has been extremely useful for my projects, and I am keenly interested in its continued development and maintenance.

Could you please provide an update on whether this repository is still actively maintained? Additionally, if there are plans for future updates or if the project is looking for contributions from the community, I would be eager to learn more about how I can be of assistance.

Thank you for your hard work on this project and for any information you can provide regarding its current status.

Best regards,
Roman

**Comment by adewes** [comment]
Hey, we're planning to ramp this up again after being busy working on other software, I'm aiming to make regular releases again and we're also working on a new hosted version. Long-term future seems a bit uncertain and is depending on how we can eventually fund the development through the hosted version or revenue, also the regulatory environment is shifting and big players like Google or IAB seem to be actively hostile towards open-source software in this area.

**Comment by saschafoerster** [comment]
@adewes I just arrived here as I tried to update and saw that the commits were not released yet, so the files under /dist are still two years old. I enjoy Klaro and would love to see it grow.
